### ISSUE TITLE
Movimiento de stock entre depositos

### ISSUE THREAD

**Issue by nhussein11** [nhussein11/sistemas3#111]
Como manejamos ahora el comprobante que estabamos creando antes al mover stock entre depositos?

Esta comentada esa funcionalidad en la linea 244 de `´src/backend/server/controllers/records/records.controller.ts´`, lo pueden ver en la rama:
[nico/backend](https://github.com/nhussein11/sistemas3/tree/nico/backend)

El trigger nose si lo podriamos sacar, condiciona logica de otras cosas

**Comment by AlejoTorres2001** [comment]
El trigger de stock lo deshabilitamos,
Vuelvo a activar el boton de crear stocks desde la pantalla de stock

(Seleccionar prod, seleccionar deposito y cant minima )

Mover stock y actualizar stock siguen funcionando igual
