### ISSUE TITLE
boton sin estilar en UpdateProductDialog

### ISSUE THREAD

**Issue by AlejoTorres2001** [nhussein11/sistemas3#17]
Holis @IVillanueva770 te estoy asignando este issue a vos.
Los issues son formas de decir a los autores del repo que algo no esta bien o que necesitan mejorarlo

En el commit 2e9741f5bc63ec090e4fe4eb561888a3622ba5d9
En el  componente **[DialogUpdateProduct](https://github.com/nhussein11/sistemas3/blob/master/components/DialogUpdateProduct.tsx)**
en la linea https://github.com/nhussein11/sistemas3/blob/master/components/DialogUpdateProduct.tsx#L42

Hay un boton sin estilos, podes estilarlo?

podes usar botones de la libreria de componentes de primereact (ver doc)
o CSS vanilla 

si encontras otros errores/mejoras abri un issue.

suerte!

**Comment by AlejoTorres2001** [comment]
Cerramos issue con
https://github.com/nhussein11/sistemas3/commit/d02927de42781bc4ef40921c4d23b8ea8f7c1688

**Comment by AlejoTorres2001** [comment]
Volve a meter tus cambios choquis

**Comment by nhussein11** [comment]
Esto está bueno si vas a hacer los estilos @IVillanueva770 
Acá te muestra como podes usar las variables css del tema (o los temas) que hayamos elegido, así toda la app sigue el mismo estándar y no tenés que buscar muchas paletas o cosas así:
[Theming with PrimeReact CSS Variables](https://www.youtube.com/watch?v=5ZudGP-1TEM&ab_channel=CagatayCivici)

**Comment by AlejoTorres2001** [comment]
esto ya esta papa
