### ISSUE TITLE
formato de precios para los productos

### ISSUE THREAD

**Issue by AlejoTorres2001** [nhussein11/sistemas3#24]
@GonzaloGuaimas 

- Signo pesos
- precio con punto separando de a miles
- punto para los decimales
- identado para la derecha

Capaz ya exista una libreria que formate precios, o ya exista algo, sino hacete un servicio

**Comment by nhussein11** [comment]
Por si no lo queres hacer a mano, capaz esta librería ayuda:
[react-number-format](https://www.npmjs.com/package/react-number-format )

- Prefix and thousand separator : 
```
<NumberFormat thousandSeparator={true} prefix={'$'} />
```

**Comment by nhussein11** [comment]
Este issue se cerró con c49cffbfa0d70616f26b9a6e5c38448408a916a7
