### ISSUE TITLE
Reestructurar el modelo de la DB

### ISSUE THREAD

**Issue by AlejoTorres2001** [nhussein11/sistemas3#27]
Sin esto no podemos seguir haciendo

Por lo menos agregar las tablas de un abm mas + redefinir la tabla productos. Ningun cambio jugado asi no metemos la pata pero como para ir haciendo algo antes del viernes que lo vemos a Cuello

**Comment by nhussein11** [comment]
Tomando el DER que tenemos en drive, tengo las siguientes dudas con las cardinalidades:
Yo lo pense así, ustedes denme el :heavy_check_mark: o no:
- En cuanto a las relaciones Producto - ProductoxDeposito - Deposito: 
![image](https://user-images.githubusercontent.com/80422357/186712628-1d2d471d-e77d-4c1b-b6dd-ba0ae6df6249.png)

Consideré lo siguiente: 
:arrow_right:  Tanto la relacion Producto - ProductoxDeposito como Deposito - ProductoxDeposito, son del tipo **1 a 1**. Pensando que si referimos a un registro de la tabla ProductoxDeposito, será considerando un producto en particular de un deposito en particular


- En cuanto a la relacion Producto - DettalleMovimiento - Movimiento - TipoMovimiento:

![image](https://user-images.githubusercontent.com/80422357/186713544-878248a8-5ca3-4235-b517-0e6ba7bb2bb2.png)

Consideré lo siguiente: 
:arrow_right:  Producto y DetalleMovimiento: **1 a N**, un producto puede aparecer en muchos detalles de movimientos (aca nose si cada detalle de movimiento es para un producto en particular)
:arrow_right: Movimiento y DetalleMovimiento: **1 a 1**, un movimiento tiene asociado un unico detalle de movimiento y viceversa
:arrow_right: Movimiento y TipoMovimiento: **1 a N**, un tipo de movimiento puede aparecer en muchos movimientos, pero cada movimiento será solo de un tipo en particular.

Por favor @GonzaloGuaimas  @IVillanueva770 @AlejoTorres2001 , corrijan si les parece bien o mal este razonamiento, así puede empezar con las apis de cada cosa

**Comment by GonzaloGuaimas** [comment]
En cuanto a la relacion Producto - DettalleMovimiento - Movimiento - TipoMovimiento:

La tabla Movimientos no tiene que tener un atributo "movimiento" sino "observación"
No sé quién puso eso pero yo le había puesto "observación"

A la Tabla TipoMovimiento le agregaría un atributo "nombre" que tendría los valores de: REMITO | FACTURA | ORDEN DE COMPRA | ORDEN DE PAGO | ETC

**Comment by AlejoTorres2001** [comment]
> Consideré lo siguiente:
> ➡️ Tanto la relacion Producto - ProductoxDeposito como Deposito - ProductoxDeposito, son del tipo **1 a 1**. Pensando que si referimos a un registro de la tabla ProductoxDeposito, será considerando un producto en particular de un deposito en particular

- Aca yo considero que un producto puede estar mencionado en 0 o mas ````ProductoXDeposito````, ***(a esta relacion podriamos renombrarla a Distribucion | Stock | Disposicion | etc)***
- Lo mismo pasa con depositos, un deposito es nombrado en 0 o mas  ````ProductoXDeposito````


> Consideré lo siguiente:
> ➡️ Producto y DetalleMovimiento: **1 a N**, un producto puede aparecer en muchos detalles de movimientos (aca nose si cada detalle de movimiento es para un producto en particular)
> ➡️ Movimiento y DetalleMovimiento: **1 a 1**, un movimiento tiene asociado un unico detalle de movimiento y viceversa
> ➡️ Movimiento y TipoMovimiento: **1 a N**, un tipo de movimiento puede aparecer en muchos movimientos, pero cada movimiento será solo de un tipo en particular.

- Para mi si un detalle referencia a un unico producto, con la cantidad y habria que ver si el precio no aparece aca directamente y no en la relacion ````Productos```` 
- El movimiento puede tener varios detalles no seria **1 a 1**  sino **N a 1**
- Entre ````Movimiento```` y ````TipoMovimiento```` si esta bien que sea **1 a N**



> En cuanto a la relacion Producto - DettalleMovimiento - Movimiento - TipoMovimiento:
> 
> La tabla Movimientos no tiene que tener un atributo "movimiento" sino "observación" No sé quién puso eso pero yo le había puesto "observación"
> 
> A la Tabla TipoMovimiento le agregaría un atributo "nombre" que tendría los valores de: REMITO | FACTURA | ORDEN DE COMPRA | ORDEN DE PAGO | ETC

con lo que dijo @GonzaloGuaimas  me parece bien que la relacion  ````Movimiento```` tenga observacion y que la relacion ````TipoMovimiento```` tenga un atributo de nombre

@nhussein11 
**Para mi con esas modificaciones estarias para arrancar el back, pero para evitar retrabajo donde lo veas medio gris espera a ver que te dice Cuello el viernes**

**Comment by nhussein11** [comment]
> En cuanto a la relacion Producto - DettalleMovimiento - Movimiento - TipoMovimiento:
> 
> La tabla Movimientos no tiene que tener un atributo "movimiento" sino "observación" No sé quién puso eso pero yo le había puesto "observación"
> 
> A la Tabla TipoMovimiento le agregaría un atributo "nombre" que tendría los valores de: REMITO | FACTURA | ORDEN DE COMPRA | ORDEN DE PAGO | ETC

De diez, queda el esquema agregando MovementNameEnum (que contiene REMITO, FACTURA, OC Y OP) y tambien la agregacion de de observacion (campo que tiene por default un espacio vacio)

**Comment by nhussein11** [comment]
> > Consideré lo siguiente:
> > arrow_right Tanto la relacion Producto - ProductoxDeposito como Deposito - ProductoxDeposito, son del tipo **1 a 1**. Pensando que si referimos a un registro de la tabla ProductoxDeposito, será considerando un producto en particular de un deposito en particular
> 
>     * Aca yo considero que un producto puede estar mencionado en 0 o mas `ProductoXDeposito`, _**(a esta relacion podriamos renombrarla a Distribucion | Stock | Disposicion | etc)**_
> 
>     * Lo mismo pasa con depositos, un deposito es nombrado en 0 o mas  `ProductoXDeposito`
> 
> 
> > Consideré lo siguiente:
> > arrow_right Producto y DetalleMovimiento: **1 a N**, un producto puede aparecer en muchos detalles de movimientos (aca nose si cada detalle de movimiento es para un producto en particular)
> > arrow_right Movimiento y DetalleMovimiento: **1 a 1**, un movimiento tiene asociado un unico detalle de movimiento y viceversa
> > arrow_right Movimiento y TipoMovimiento: **1 a N**, un tipo de movimiento puede aparecer en muchos movimientos, pero cada movimiento será solo de un tipo en particular.
> 
>     * Para mi si un detalle referencia a un unico producto, con la cantidad y habria que ver si el precio no aparece aca directamente y no en la relacion `Productos`
> 
>     * El movimiento puede tener varios detalles no seria **1 a 1**  sino **N a 1**
> 
>     * Entre `Movimiento` y `TipoMovimiento` si esta bien que sea **1 a N**
> 
> 
> > En cuanto a la relacion Producto - DettalleMovimiento - Movimiento - TipoMovimiento:
> > La tabla Movimientos no tiene que tener un atributo "movimiento" sino "observación" No sé quién puso eso pero yo le había puesto "observación"
> > A la Tabla TipoMovimiento le agregaría un atributo "nombre" que tendría los valores de: REMITO | FACTURA | ORDEN DE COMPRA | ORDEN DE PAGO | ETC
> 
> con lo que dijo @GonzaloGuaimas me parece bien que la relacion `Movimiento` tenga observacion y que la relacion `TipoMovimiento` tenga un atributo de nombre
> 
> @nhussein11 **Para mi con esas modificaciones estarias para arrancar el back, pero para evitar retrabajo donde lo veas medio gris espera a ver que te dice Cuello el viernes**

- Las relaciones que deberían ser 0 a N (ó 0-1), creo que se solventan poniendo default vacion en la FK, asi lo resolvi pero si llegan a encontrar una solucion mas "formal", bienvenido sea
- Modificado el nombre "ProductxStore"  --> "Stock" :heavy_check_mark: 
- "El movimiento puede tener varios detalles no seria 1 a 1 sino N a 1"  :heavy_check_mark: 

- [ ] Duda para cuello:

 "Para mi si un detalle referencia a un unico producto, con la cantidad y habria que ver si el precio no aparece aca directamente y no en la relacion Productos"

**Comment by nhussein11** [comment]
Los cambios :heavy_check_mark:  se ven en ee4e373c870f73baae9d158593fc23978f7c0215 por cualquier cosa

**Comment by AlejoTorres2001** [comment]
Este issue se cerro con 8ab9853df361e0e74a8cd04e2a1621f283da4f82
