### ISSUE TITLE
Error creando/actualizando Productos con precios que tengan numeros decimales

### ISSUE THREAD

**Issue by AlejoTorres2001** [nhussein11/sistemas3#30]
## Si creas/ actualizas un precio de un producto a un numero con decimales Ej: 123.23, Devuelve codigo de error ````500````

- El servicio del frontend [createNewProduct](https://github.com/nhussein11/sistemas3/blob/master/src/frontend/services/createNewProduct.ts) esta ````typesafe```` y requiere un number ✅ 
- En [useDialogNewProductMutation](https://github.com/nhussein11/sistemas3/blob/master/src/frontend/hooks/products/useDialogNewProductMutation.tsx#L16) El estado es de tipo ````number```` ✅
- En [products.controller](https://github.com/nhussein11/sistemas3/blob/master/src/backend/server/controllers/products/products.controller.ts#L14) chequeando ```` typeof price```` llega un ````number```` ✅

- En [schema.prisma](https://github.com/nhussein11/sistemas3/blob/master/src/backend/prisma/schema.prisma#L16) el precio es de tipo int ❌ 

**podes buscar un tipo de dato que solucione esto y correr la migracion?**

**Comment by nhussein11** [comment]
Cambié en la base de datos el tipo int a float (lo cual es una pesima idea al parecer: https://stackoverflow.com/questions/15726535/postgresql-which-datatype-should-be-used-for-currency)

Previamente use el tipo de dato Decimal @db.decimal(12,2). El inconveniente de esta solución es que entra en conflicto con la librería react-number-format:
Mostrando por ejemplo: $ 12.33 de la forma $ 1.233 (el thousandSeparator, busca 3 lugares y añade un punto, independientemente del tipo de dato)

Si se puede cambiar esto a futuro y usar  Decimal @db.decimal(12,2) sería lo mejor

**Comment by AlejoTorres2001** [comment]
@GonzaloGuaimas @IVillanueva770 
Nico cambio la definicion de tablas,pero creo que no subio los cambios en el archivo ````prisma.schema````
probe cambiando el tipo de dato que tenia ````price```` a ````float````
```javascript
model Products{
  id String @id @default(cuid())
  name String
  price Float  //antes era Int
}
```
y corriendo ````npx prisma generate --schema='./src/backend/prisma/schema.prisma'````
generamos un nuevo cliente que cumple con las definiciones en ````prisma.schema````
haciendo esto anda el CRUD completo, entonces:

@nhussein11 creo que corriste una migracion con tus cambios, pero como vos decis que se veia feo con la libreria de ````react-number-format```` no incluiste esos cambios en ningun lugar, pero a la BD no la restauraste a un estado anterior. 
- Fijate si tenes cambios para subir, sino deja el precio en float (o en decimal con 2 numeros despues de la coma) 
- Despues corre una migracion para impactar el modelo nuevo en la base de datos de Heroku

Cuando nico vea esto y de el ✅  renueven sus clientes de prisma con el comando:  
 ````npx prisma generate --schema='./src/backend/prisma/schema.prisma'````

(nico vos tambien por las dudas, pero creo que al migrar te lo hace solo)

**Comment by nhussein11** [comment]
Reemplazo 
```
model Products{
  id String @id @default(cuid())
  name String
  price Float @db.Real
}
```

Y cierro este issue con e06b94cc2d3ff85f07f1a263299a6456a6b07adc
