### ISSUE TITLE
Formularios de crear y actualizar prods coincidentes con la bd

### ISSUE THREAD

**Issue by nhussein11** [nhussein11/sistemas3#45]
Gonza te animas a crear un input "description" en cada dialogo de creacion y acutalización de producto:
`'src/frontend/components/products/DialogNewProduct.tsx'`
`'src/frontend/components/products/DialogUpdateProduct.tsx'`

La base de datos necesita nombre, precio y descripción para poder crear un producto, al agregar este campo descripcion se soluciona el error
:rocket:

**Comment by GonzaloGuaimas** [comment]
oki

**Comment by AlejoTorres2001** [comment]
@GonzaloGuaimas acordate que ahora esta el hook UseField
https://github.com/nhussein11/sistemas3/blob/master/src/frontend/hooks/useField.tsx

**Comment by nhussein11** [comment]
Cerramos con 724c2be38f72f3508d8afd198ad14a8d6c25f077 :100:

**Comment by nhussein11** [comment]
Hola @GonzaloGuaimas , agregué el campo que pidió cuello "category" a products...
Te animas a hacer exactamente lo mismo que hiciste con "descripcion", pero ahora con "categoria" ? :pray: 

Fijate que este campo lo puse como enum, si pones un dropdown sería lo mejor, los valores posibles son "IMPRESORA" y "FILAMENTO".

Te dejo dos ejemplos  de post de producto para que te guies:
```

{
  "name":"impresora 3d",
  "price":5214.25,
  "description":"super impresora",
  "category":"IMPRESORA"
}
```

```
{
  "name":"filamento azul",
  "price":520.5,
  "description":"filamento super fachero",
  "category":"FILAMENTO"
}
```

**Comment by GonzaloGuaimas** [comment]
Quise mergear todos los cambios que hice pero me tiro que hubo un error, no sé porque si estaba todo bien :/

**Comment by nhussein11** [comment]
Ahi esta el error:
![image](https://user-images.githubusercontent.com/80422357/187185946-4798c649-b4bf-4112-8991-cd5999f024e2.png)

El tipo de dato de categoria no es string, es un enum que se importa directamente de:

`import { CategoryEnum } from '@prisma/client'
`

En el tipo producto podes ver el uso:
`'src/shared/schemas/product.type.ts'`

**Comment by nhussein11** [comment]
Al crear un producto, el metodo en el servidor requiere 3 atributos adicionales a los que ya estan: storeId (id del deposito en donde se esta registrado ese producto), quantity (cantidad del productoq se esta registrando) y minQuantity (cantidad minima de ese producto por deposito)
[Ese ultimo atributo tal vez requiera  separar la logica  (en el front y en el back) para los casos en los cuales el producto y su cantudad minima ya este registradas]
```
const createProduct = async (
  name: string,
  price: number,
  description: string,
  category: CategoryEnum,
  storeId: string,
  quantity: number,
  minQuantity: number
) => {...}
```

Por favor, hacer el frontend para considerar el envio de esos datos también al servidor

**Comment by AlejoTorres2001** [comment]
@nhussein11  Me pongo con el abm de Depositos (Stores) primero, despues arreglo los servicios / interfaz del abm de productos

**Comment by AlejoTorres2001** [comment]
Nada me hace ***mas feliz*** que cerrar este issue con 220c4384af0c0fdd4e785c2900939975d02e82d0
