### ISSUE TITLE
Schemas duplicados

### ISSUE THREAD

**Issue by nhussein11** [nhussein11/sistemas3#57]
Los tipos de datos almacenados en:
'src/shared/schemas'

Son coincidentes con todos los que genera prisma ubicados en:
 'node_modules/.prisma/client/index.d.ts'

Se podría eliminar la carpeta 'src/shared/schemas', y hacer que tanto backend como frontend soliciten de la misma fuente

**Comment by AlejoTorres2001** [comment]
Mandale mecha @nhussein11

**Comment by AlejoTorres2001** [comment]
@nhussein11  con #61 y #45 ````closed````, Ahora si podrias revisar esto de nuevo
