### ISSUE TITLE
Actualizacion de un Stock

### ISSUE THREAD

**Issue by AlejoTorres2001** [nhussein11/sistemas3#67]
Existe un bug al actualizar Stocks de productos, pasando de un deposito, a otro ,el cual ya contiene stock de ese producto

### Comportmiento actual:

Al actualizar el Stock de un producto y pasarlo a otro deposito, **se crean 2 registros de Stock**, del mismo producto en el mismo deposito, ***pero con cantidades diferentes***

### Como reproducir:

- crear un registro de  ````Stock````
- crear otro registro de  ````Stock````, mismo  ````Producto````, distinto ````Store```` 
- actualizar uno de los registros, haciendo coincidir los ````Store```` 

### Comportamiento deseado:

Al actualizar un ````Stock````, se deberia chequear que, **Si existe un stock de ESE producto en el ````Store```` al cual se esta actualizando, juntar ambos registros para evitar "duplicados"** de registros de ````Stock```` de un mismo ````producto```` en un mismo ````Store````

- Esto se debria realizar en el endpoint correspondiente a la **actualizacion de Stocks**, *antes* de enviar una respuesta al cliente. (sino perdemos la revalidacion de la query de ````Stocks```` correspondiente a ````react-query````)

**Comment by nhussein11** [comment]
En ese caso, necesito que me mandes el productId en esa operacion para poder hacer la busqueda
Dejo mi parte en #71

**Comment by AlejoTorres2001** [comment]
El productId lo podes obtener usando el id del Stock, ya que dijimos que no ibamos a permitir actualizar el producto de ese stock, solo cantidades y el deposito donde esta

**Comment by nhussein11** [comment]
Eso hace #71 
Fijate la logica nueva de update stock, solo pido el productId para buscarlo (lo uso en la funcion getExistingStock) pero nunca actualizo el productId

**Comment by AlejoTorres2001** [comment]
Incluido en #72

**Comment by nhussein11** [comment]
Por ahora cerramos con #77
