### ISSUE TITLE
Boton de borrar producto y deposito no funciona correctamente

### ISSUE THREAD

**Issue by nhussein11** [nhussein11/sistemas3#68]
Supongo yo que por integridad refencial (ambos id's son fk's en la tabla stock), en ese caso tal vez se debería mostrar otro mensaje al usuario o manejar de otra manera el "id not provided" que mostramos actualmente

**Comment by AlejoTorres2001** [comment]
osea que si tratas de borrar algo que esta refrenciado mostrar otro error?
si me pasas un errorMessage desde el servidor lo puedo mostrar en el DIalogError

**Comment by AlejoTorres2001** [comment]
ver #69

**Comment by nhussein11** [comment]
cierro con #70
