### ISSUE TITLE
decoupling prismaClient instance from controller logic

### ISSUE THREAD

**Issue by AlejoTorres2001** [nhussein11/sistemas3#7]
On 4eb36af5004e9b5e539c677d4581275fb0777fde
at https://github.com/nhussein11/sistemas3/blob/master/server/controllers/products/products.controller.ts#L3
Prisma client should be decoupled from the  products controller's logic and available to other controllers.

Should be only one PrismaClient instance as per the documentation
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/instantiate-prisma-client

## Re-using a single PrismaClient instance
To re-use a single instance, create a module that exports a PrismaClient object:

```javascript
//client.ts
import { PrismaClient } from '@prisma/client'

let prisma = new PrismaClient()

export default prisma
```

**Comment by nhussein11** [comment]
If Next.js refreshes the module responsible for exporting PrismaClient, probably we should store Prisma Client as a global variable in development environments only. 
Following this piece of code:

```
import { PrismaClient } from '@prisma/client'

// add prisma to the NodeJS global type
interface CustomNodeJsGlobal extends NodeJS.Global {
  prisma: PrismaClient
}

// Prevent multiple instances of Prisma Client in development
declare const global: CustomNodeJsGlobal

const prisma = global.prisma || new PrismaClient()

if (process.env.NODE_ENV === 'development') global.prisma = prisma

export default prisma
```

**Comment by AlejoTorres2001** [comment]
In https://github.com/prisma/docs/issues/1391

- looks like Prisma doc is outdated in the following link https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prevent-hot-reloading-from-creating-new-instances-of-prismaclient

- But it show a similar code snippet suggested by https://github.com/prisma/docs/issues/1391#issuecomment-932810642 on:
https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices



> If Next.js refreshes the module responsible for exporting PrismaClient, probably we should store Prisma Client as a global variable in development environments only. Following this piece of code:
> 
> ```
> import { PrismaClient } from '@prisma/client'
> 
> // add prisma to the NodeJS global type
> interface CustomNodeJsGlobal extends NodeJS.Global {
>   prisma: PrismaClient
> }
> 
> // Prevent multiple instances of Prisma Client in development
> declare const global: CustomNodeJsGlobal
> 
> const prisma = global.prisma || new PrismaClient()
> 
> if (process.env.NODE_ENV === 'development') global.prisma = prisma
> 
> export default prisma
> ```

looks like the above code gives issues when Ts on strict-mode using  ````@types/node>16````

I suggest using the following 
 ```Javascript
import { PrismaClient } from '@prisma/client'

declare global {
  // allow global `var` declarations
  var prisma: PrismaClient | undefined
}

export const prisma =
  global.prisma ||
  new PrismaClient({
    log: ['query'],
  })

if (process.env.NODE_ENV !== 'production') global.prisma = prisma
 ```
